name: Generate Dart
on: [push]
jobs:
  generate-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
      - name: Install Open Api Generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Generate Dart Files
        run: npm run generate-dart
